### ISSUE TITLE
Suggested PowerShell Installation fails

### ISSUE THREAD

**Issue by ivancmz** [espressif/idf-env#53]
Hi, on the readme.md there's a suggested way of installing on PowerShell:

`Invoke-WebRequest 'https://dl.espressif.com/dl/idf-env/idf-env.exe' -OutFile .\idf-env.exe; .\idf-env.exe driver install --espressif --ftdi --silabs --wch`

But I get the following output:
```
thread 'main' panicked at 'internal error: entered unreachable code: Bad help structure (doesn't match with path)', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\clap-nested-0.4.0\src\lib.rs:343:25
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The file gets downloaded, I can use it. What I believe is failling is the drivers installation.

**Comment by ivancmz** [comment]
Yes, when I try only this after the file is downloaded it also fails:
```
.\idf-env.exe driver install --espressif --ftdi --silabs --wch
thread 'main' panicked at 'internal error: entered unreachable code: Bad help structure (doesn't match with path)', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\clap-nested-0.4.0\src\lib.rs:343:25
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I also tried on an elevated powershell (administrator) tab.

**Comment by ivancmz** [comment]
It works when I remove  --wch option!

**Comment by ShawnHymel** [comment]
Thanks for the heads up! It looks like the README is out of date. I got it to work by using the command on this doc page: https://docs.espressif.com/projects/esp-idf/en/stable/esp32s3/api-guides/jtag-debugging/configure-builtin-jtag.html
